spring.application.name=Last
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/cricket_app
spring.datasource.username=root
spring.datasource.password=Satnamji30@@

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.springframework=DEBUG
logging.level.org.hibernate.tool.hbm2ddl=INFO

spring.security.user.name=milap
spring.security.user.password=milap@123
logging.level.org.springframework.web=DEBUG
server.error.include-message=always
server.error.include-binding-errors=always

logging.level.org.springframework.security=DEBUG


